apiVersion: v1
kind: Service
metadata:
   namespace: third-party
   name: consul
   labels:
     name: consul
spec:
   clusterIP: None
   ports:
    - name: http
      port: 8500
      targetPort: 8500
    - name: https
      port: 8443
      targetPort: 8443
    - name: rpc
      port: 8400
      targetPort: 8400
    - name: serflan-tcp
      protocol: "TCP"
      port: 8301
      targetPort: 8301
    - name: serflan-udp
      protocol: "UDP"
      port: 8301
      targetPort: 8301
    - name: serfwan-tcp
      protocol: "TCP"
      port: 8302
      targetPort: 8302
    - name: serfwan-udp
      protocol: "UDP"
      port: 8302
      targetPort: 8302
    - name: server
      port: 8300
      targetPort: 8300
    - name: consuldns
      port: 8600
      targetPort: 8600
   selector:
    app: consul
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: "consul-pdb"
  namespace: third-party
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: "consul"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: consul
  labels:
    app: consul
  namespace: third-party
spec:
  podManagementPolicy: "OrderedReady"  #逐一创建
  serviceName: consul
  replicas: 3
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      affinity:
        nodeAffinity:
          # 优先先择节点亲和标签，如果没有符合的可以在其它节点运行
          #preferredDuringSchedulingIgnoredDuringExecution:
          #- weight: 1
          #  preference:
          # 强制选择带标签的节点，一直重试
          requiredDuringSchedulingIgnoredDuringExecution:
           nodeSelectorTerms:
            - matchExpressions:
              - key: tzwken/consul
                operator: In
                values:
                - "consul"
        podAntiAffinity:
          # 节点反亲和
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - "consul"
            topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 180
      containers:
      - name: consul
        image: consul:1.8.3
        command:
         - /bin/consul
        args:
             - "agent"
             - "-server"
             - "-bootstrap-expect=3"
             - "-ui"
             - "-data-dir=/consul/data"
             - "-bind=0.0.0.0"
             - "-client=0.0.0.0"
             - "-advertise=$(PODIP)"
             - "-retry-join=consul-0.consul.$(NAMESPACE).svc.cluster.local"
             - "-retry-join=consul-1.consul.$(NAMESPACE).svc.cluster.local"
             - "-retry-join=consul-2.consul.$(NAMESPACE).svc.cluster.local"
             - "-domain=cluster.local"
             - "-disable-host-node-id"
        env:
            - name: PODIP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
        resources:
            limits:
              cpu: '2'
              memory: 1000Mi
            requests:
              cpu: 500m
              memory: 500Mi
        ports:
            - containerPort: 8500
              name: ui-port
            - containerPort: 8400
              name: alt-port
            - containerPort: 53
              name: udp-port
            - containerPort: 8443
              name: https-port
            - containerPort: 8080
              name: http-port
            - containerPort: 8301
              name: serflan
            - containerPort: 8302
              name: serfwan
            - containerPort: 8600
              name: consuldns
            - containerPort: 8300
              name: server
        imagePullPolicy: IfNotPresent