kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
  namespace: third-party
  labels:
    app: elasticsearch
spec:
  ports:
    - name: http
      protocol: TCP
      port: 9200
      targetPort: 9200
    - name: transport
      protocol: TCP
      port: 9300
      targetPort: 9300
  selector:
    app: es
  clusterIP: None
  type: ClusterIP

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: es
  namespace: third-party
  labels:
    app: es
spec:
  replicas: 3
  selector:
    matchLabels:
      app: es
  template:
    metadata:
      name: es
      creationTimestamp: null
      labels:
        app: es
    spec:
      volumes:
        - name: esdata
          hostPath:
            path: /data/k8s/esdata
            type: DirectoryOrCreate
        - name: jvm-options
          configMap:
            name: jvm-options
            items:
              - key: jvm.options
                path: jvm.options
            defaultMode: 420
      initContainers:
        - name: configure-sysctl
          image: 'registry.cn-beijing.aliyuncs.com/onpremise/es:5.6-alpine'
          command:
            - sh
            - '-c'
            - >
              sysctl -w vm.max_map_count=262144 ; chown 100:101 /esdata -R;
              sysctl -w net.ipv4.ping_group_range="0 2147483647"
          resources: {}
          volumeMounts:
            - name: esdata
              mountPath: /esdata
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
            runAsUser: 0
      containers:
        - name: elasticsearch
          image: 'registry.cn-beijing.aliyuncs.com/onpremise/es:5.6-alpine'
          args:
            - '-E'
            - cluster.name=es-k1aktq97
            - '-E'
            - node.name=$(node.name)
            - '-E'
            - network.bind_host=0.0.0.0
            - '-E'
            - '-E'
            - network.publish_host=$(node.ip)
            - '-E'
            - path.data=/esdata
            - '-E'
            - discovery.zen.minimum_master_nodes=2
            - '-E'
            - discovery.zen.publish_timeout=2s
            - '-E'
            - discovery.zen.no_master_block=write
            - '-E'
            - discovery.zen.ping_timeout=1s
            - '-E'
            - discovery.zen.fd.ping_timeout=3s
            - '-E'
            - discovery.zen.fd.ping_retries=3
            - '-E'
            - discovery.zen.ping.unicast.hosts=es-0.elasticsearch.third-party.svc.cluster.local.,es-1.elasticsearch.third-party.svc.cluster.local.,es-2.elasticsearch.third-party.svc.cluster.local.
          ports:
            - name: http
              containerPort: 9200
              protocol: TCP
            - name: transport
              containerPort: 9300
              protocol: TCP
          env:
            - name: node.name
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: node.ip
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: ES_JAVA_OPTS
              value: '-Duser.timezone=Asia/Shanghai'
          resources:
            limits:
              cpu: '2'
              memory: 4Gi
            requests:
              cpu: 100m
              memory: 2Gi
          volumeMounts:
            - name: esdata
              mountPath: /esdata
          readinessProbe:
            exec:
              command:
                - sh
                - '-c'
                - |
                  #!/usr/bin/env bash -e
                  START_FILE=/tmp/.es_start_file
                  http () {
                      local path="${1}"
                      if [ -n "${ELASTIC_USERNAME}" ] && [ -n "${ELASTIC_PASSWORD}" ]; then
                        BASIC_AUTH="-u ${ELASTIC_USERNAME}:${ELASTIC_PASSWORD}"
                      else
                        BASIC_AUTH=''
                      fi
                      curl -XGET -s -k --fail ${BASIC_AUTH} http://127.0.0.1:9200${path}
                  }
                  if [ -f "${START_FILE}" ]; then
                      echo 'Elasticsearch is already running, lets check the node is healthy and there are master nodes available'
                      http "/_cluster/health?timeout=0s"
                      exit 0
                  else
                      echo 'Waiting for elasticsearch cluster to become cluster to be ready (request params: "wait_for_status=green&timeout=1s" )'
                      if http "/_cluster/health?wait_for_status=green&timeout=1s" ; then
                          touch ${START_FILE}
                          exit 0
                      else
                          NUM=0
                          for i in `seq 0 2`;
                          do
                            nc -nz es-$i.elasticsearch.third-party.svc.cluster.local  9300
                            if [ $? -eq 0 ]; then
                              NUM=$((NUM+1))
                            fi
                          done
                          if [ ${NUM} -eq 0 ]; then
                            exit 0
                          fi
                          echo 'Cluster is not yet ready (request params: "wait_for_status=green&timeout=1s" )'
                          exit 1
                      fi
                  fi
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 10
            successThreshold: 2
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              drop:
                - ALL
            runAsUser: 100
            runAsNonRoot: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 120
      dnsPolicy: ClusterFirst
      securityContext:
        runAsUser: 100
        fsGroup: 101
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: tzwken/es
                    operator: In
                    values:
                      - elasticsearch
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - es
              topologyKey: kubernetes.io/hostname
      schedulerName: default-scheduler
      tolerations:
        - operator: Exists
          effect: NoSchedule
  serviceName: elasticsearch
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  revisionHistoryLimit: 10
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: jvm-options
  namespace: third-party
data:
  jvm.options: >
    ## JVM configuration

    ################################################################

    ## IMPORTANT: JVM heap size

    ################################################################

    ##

    ## You should always set the min and max JVM heap

    ## size to the same value. For example, to set

    ## the heap to 4 GB, set:

    ##

    ## -Xms4g

    ## -Xmx4g

    ##

    ## See
    https://www.elastic.co/guide/en/elasticsearch/reference/current/heap-size.html

    ## for more information

    ##

    ################################################################

    # Xms represents the initial size of total heap space

    # Xmx represents the maximum size of total heap space

    -Xms2g

    -Xmx2g

    ################################################################

    ## Expert settings

    ################################################################

    ##

    ## All settings below this section are considered

    ## expert settings. Don't tamper with them unless

    ## you understand what you are doing

    ##

    ################################################################

    ## GC configuration

    #-XX:+UseConcMarkSweepGC

    #-XX:CMSInitiatingOccupancyFraction=75

    #-XX:+UseCMSInitiatingOccupancyOnly

    -XX:+UseContainerSupport

    -XX:InitialRAMPercentage=60.0

    -XX:MinRAMPercentage=40.0

    -XX:MaxRAMPercentage=80.0

    -XX:+UseG1GC

    -XX:MaxGCPauseMillis=200

    -XX:InitiatingHeapOccupancyPercent=60

    ## optimizations

    # pre-touch memory pages used by the JVM during initialization

    -XX:+AlwaysPreTouch

    ## basic

    # force the server VM (remove on 32-bit client JVMs)

    -server

    # explicitly set the stack size (reduce to 320k on 32-bit client JVMs)

    -Xss1m

    # set to headless, just in case

    -Djava.awt.headless=true

    # ensure UTF-8 encoding by default (e.g. filenames)

    -Dfile.encoding=UTF-8

    # use our provided JNA always versus the system one

    -Djna.nosys=true

    # use old-style file permissions on JDK9

    -Djdk.io.permissionsUseCanonicalPath=true

    # flags to configure Netty

    -Dio.netty.noUnsafe=true

    -Dio.netty.noKeySetOptimization=true

    -Dio.netty.recycler.maxCapacityPerThread=0

    # log4j 2

    -Dlog4j.shutdownHookEnabled=false

    -Dlog4j2.disable.jmx=true

    -Dlog4j.skipJansi=true

    ## heap dumps

    # generate a heap dump when an allocation from the Java heap fails

    # heap dumps are created in the working directory of the JVM

    -XX:+HeapDumpOnOutOfMemoryError

    # specify an alternative path for heap dumps

    # ensure the directory exists and has sufficient space

    #-XX:HeapDumpPath=${heap.dump.path}

    ## GC logging

    #-XX:+PrintGCDetails

    #-XX:+PrintGCTimeStamps

    #-XX:+PrintGCDateStamps

    #-XX:+PrintClassHistogram

    #-XX:+PrintTenuringDistribution

    #-XX:+PrintGCApplicationStoppedTime

    # log GC status to a file with time stamps

    # ensure the directory exists

    #-Xloggc:${loggc}

    # By default, the GC log file will not rotate.

    # By uncommenting the lines below, the GC log file

    # will be rotated every 128MB at most 32 times.

    #-XX:+UseGCLogFileRotation

    #-XX:NumberOfGCLogFiles=32

    #-XX:GCLogFileSize=128M

    # Elasticsearch 5.0.0 will throw an exception on unquoted field names in
    JSON.

    # If documents were already indexed with unquoted fields in a previous
    version

    # of Elasticsearch, some operations may throw errors.

    #

    # WARNING: This option will be removed in Elasticsearch 6.0.0 and is
    provided

    # only for migration purposes.

    #-Delasticsearch.json.allow_unquoted_field_names=true
