apiVersion: v1
items:
- apiVersion: v1
  data:
    allow-backend-server-header: "true"
    compute-full-forwarded-for: "true"
    enable-underscores-in-headers: "true"
    forwarded-for-header: X-Forwarded-For
    generate-request-id: "true"
    ignore-invalid-headers: "true"
    max-worker-connections: "65536"
    proxy-body-size: 100m
    proxy-connect-timeout: "240"
    proxy-read-timeout: "240"
    proxy-send-timeout: "240"
    reuse-port: "true"
    server-tokens: "false"
    ssl-redirect: "false"
    use-forwarded-headers: "true"
    worker-cpu-affinity: auto
    worker-processes: '4'
  kind: ConfigMap
  metadata:
    labels:
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/part-of: ingress-nginx
    name: nginx-configuration
    namespace: ingress-nginx
- apiVersion: v1
  kind: ConfigMap
  metadata:
    labels:
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/part-of: ingress-nginx
    name: tcp-services
    namespace: ingress-nginx
- apiVersion: v1
  kind: ConfigMap
  metadata:
    labels:
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/part-of: ingress-nginx
    name: udp-services
    namespace: ingress-nginx
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
